<?php

namespace WS\OvsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends EntityRepository {

    public function findDateValide($date) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect('COUNT(ue.user) as nombre')
                ->innerJoin('e.userEvenements', 'ue')
                ->where('e.actif = :actif')
                ->setParameter('actif', 1)
                ->andWhere('e.date = :date')
                ->setParameter('date', $date)
                ->andWhere('ue.statut = :statut')
                ->setParameter('statut', 'Validé')
                ->groupBy('e.id')
                ->orderBy('e.heure', 'ASC');
        return $qb->getQuery()->getArrayResult();
    }

}
