<?php

namespace WS\OvsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEvenementRepository extends EntityRepository {

    public function findActif() {
        return $this
                        ->createQueryBuilder('ue')
                        ->where('ue.actif = :actif')
                        ->setParameter('actif', 1)
        ;
    }

}
