<?php

namespace WS\OvsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEvenementRepository extends EntityRepository {

    public function findActif() {
        return $this
                        ->createQueryBuilder('ue')
                        ->where('ue.actif = :actif')
                        ->setParameter('actif', 1)
        ;
    }

    /**
     *
     * @param type $statut
     * @param type $evenement
     * @return type
     *
     * Méthode qui va renvoyer la liste des participant trier par nom.
     */
    public function listeTrierUsername($statut, $evenement) {
        $qb = $this->createQueryBuilder('ue');
        $qb->where('ue.actif=:actif')
                ->setParameter('actif', 1)
                ->andWhere('ue.statut=:statut')
                ->setParameter('statut', $statut)
                ->andWhere('ue.evenement=:evenement')
                ->setParameter('evenement', $evenement)
                ->leftJoin('ue.user', 'u')
                ->orderBy('u.username');
        return $qb->getQuery()->getResult();
    }

}
