<?php

namespace WS\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageboxRepository extends EntityRepository {

    public function ListChats($user) {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.emetteur=:emetteur')
                ->setParameter('emetteur', $user)
                ->groupBy('m.recepteur');
        return $qb->getQuery()->getResult();
    }

}
