<?php

namespace WS\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageboxRepository extends EntityRepository {

}
