<?php

namespace WS\OvsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \WS\OvsBundle\Controller\DateController();
        return $instance;
    }
}
